name: Snyk SCA, Code, IaC and Container CLI monitor example

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  snyk-scan:
    runs-on: ubuntu-latest

    strategy:
      matrix:
          node-version: [20.x]  # ✅ Use 18.13.0 ou superior (20.x é recomendado)

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
         
      #- name: Set up Node.js
        #uses: actions/setup-node@v4
        #with:
          #node-version: '16'

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Configure Snyk CLI environment
        run: snyk config environment SNYK-US-02

      - name: Authenticate Snyk CLI
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk auth "$SNYK_TOKEN"

      - name: Install project dependencies
        run: npm install

      - name: Run Snyk Open Source Test (SCA)
        run: snyk test || true

      - name: Monitor Open Source Project
        run: snyk monitor

      - name: Run Snyk Code Test
        run: snyk code test || true

      - name: Build Docker Image
        run: docker build . -t juice-shop:test

      - name: Monitor Docker Image
        run: snyk container monitor juice-shop:test --file=Dockerfile

      - name: Run Snyk IaC Test
        run: snyk iac test || true
