name: Snyk SCA, Code, IaC and Container CLI monitor example

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Snyk Scan Pipeline
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
            node-version: ${{ matrix.node-version }}
            cache: "npm"

      - name: Install Snyk CLI and snyk-to-html
        run: |
          npm install -g snyk snyk-to-html

      - name: Authenticate Snyk CLI
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk auth "$SNYK_TOKEN"

      - name: Run Snyk Open Source Test (SCA)
        run: snyk test || true

      - name: Monitor Open Source Project
        run: snyk monitor

      - name: Run Snyk Code Test
        run: snyk code test || true

      - name: Build Docker Image
        run: docker build . -t juice-shop:test

      - name: Monitor Docker Image
        run: snyk container monitor juice-shop:test --file=Dockerfile

      - name: Run Snyk IaC Test
        run: snyk iac test || true

      - name: Generate Snyk HTML Report
        run: |
          snyk test --json > snyk-results.json
          snyk-to-html -i snyk-results.json -o snyk-report.html

      - name: Upload HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: snyk-html-report
          path: snyk-report.html
