name: Snyk SCA, Code, IaC and Container CLI monitor example

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  snyk-scan:
    runs-on: ubuntu-latest

    steps:

      - name: Configure Snyk environment
        run: snyk config environment SNYK-US-02  # Substitua pelo identificador do seu ambiente

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Authenticate Snyk CLI
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          SNYK_API: https://app.us.snyk.io
        run: snyk auth "$SNYK_TOKEN"

      - name: Run Snyk Open Source Test (SCA)
        run: snyk test || true

      - name: Monitor Open Source Project
        run: snyk monitor

      - name: Run Snyk Code Test
        run: snyk code test || true

      - name: Build Docker Image
        run: docker build . -t juice-shop:test

      - name: Monitor Docker Image
        run: snyk container monitor juice-shop:test --file=Dockerfile

      - name: Run Snyk IaC Test
        run: snyk iac test || true
